// Copyright © from 2024 to present, UNKNOWN STRYKER. All Rights Reserved. 
#include <FE/framework/reflection/private/load_reflection_data.h> 
#include <FE/framework.h> 
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/type_info.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/smart_ptr.hxx>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/framework.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/reflection.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/system.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/ECS.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/thread_id.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/archetype_base.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/reflection.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/game.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/component_base.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework.h>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/reflection/private/load_reflection_data.h>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/world.hpp>
#include <C:/Users/leeho/Documents/GitHub/Frogman-Engine/SDK/CMake/../Framework/Include/FE/framework/processors.hpp>


void serialize_component_FE_framework_internal_processors_reachability_analysis_arguments(::std::pmr::string& out_buffer_p, ::FE::component_base* const component_p, ::FE::ASCII* const version_p) noexcept
{
    ::FE::framework::framework_base::get_framework().get_property_reflection().serialize(out_buffer_p, *::FE::polymorphic_cast<::FE::framework::internal::processors::reachability_analysis_arguments* const>(component_p), version_p);
}

void deserialize_component_FE_framework_internal_processors_reachability_analysis_arguments(const ::std::pmr::string& buffer_p, ::FE::component_base* const component_p, ::FE::ASCII* const version_p) noexcept
{
    ::FE::framework::framework_base::get_framework().get_property_reflection().deserialize(buffer_p, *::FE::polymorphic_cast<::FE::framework::internal::processors::reachability_analysis_arguments* const>(component_p), version_p);
}


void load_reflection_data()
{
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::cpp_style_task<::FE::framework::ECS, ::FE::entity<::FE::archetype_base>(::FE::ASCII* const, ::FE::framework::initializer&)> >("::FE::world", &::FE::framework::ECS::instanciate_entity_from_initializer<::FE::world>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::cpp_style_task<::FE::framework::ECS, void(::FE::entity<::FE::archetype_base>)> >("~::FE::world", &::FE::framework::ECS::destruct_entity);

    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::cpp_style_task<::FE::framework::ECS, ::FE::entity<::FE::archetype_base>(::FE::ASCII* const, ::FE::framework::initializer&)> >("::FE::game", &::FE::framework::ECS::instanciate_entity_from_initializer<::FE::game>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::cpp_style_task<::FE::framework::ECS, void(::FE::entity<::FE::archetype_base>)> >("~::FE::game", &::FE::framework::ECS::destruct_entity);

    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::archetype_base*(::FE::archetype_base*)> >("construct ::FE::archetype_base", &::std::construct_at<::FE::archetype_base>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::archetype_base*)> >("destruct ::FE::archetype_base", &::std::destroy_at<::FE::archetype_base>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::type_info*(::FE::framework::reflection::type_info*)> >("construct ::FE::framework::reflection::type_info", &::std::construct_at<::FE::framework::reflection::type_info>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::type_info*)> >("destruct ::FE::framework::reflection::type_info", &::std::destroy_at<::FE::framework::reflection::type_info>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::internal::type_info::metadata*(::FE::framework::reflection::internal::type_info::metadata*)> >("construct ::FE::framework::reflection::internal::type_info::metadata", &::std::construct_at<::FE::framework::reflection::internal::type_info::metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::internal::type_info::metadata*)> >("destruct ::FE::framework::reflection::internal::type_info::metadata", &::std::destroy_at<::FE::framework::reflection::internal::type_info::metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::component_base*(::FE::component_base*)> >("construct ::FE::component_base", &::std::construct_at<::FE::component_base>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::component_base*)> >("destruct ::FE::component_base", &::std::destroy_at<::FE::component_base>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::internal::ECS::components*(::FE::internal::ECS::components*)> >("construct ::FE::internal::ECS::components", &::std::construct_at<::FE::internal::ECS::components>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::internal::ECS::components*)> >("destruct ::FE::internal::ECS::components", &::std::destroy_at<::FE::internal::ECS::components>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::internal::ECS::gc_metadata*(::FE::internal::ECS::gc_metadata*)> >("construct ::FE::internal::ECS::gc_metadata", &::std::construct_at<::FE::internal::ECS::gc_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::internal::ECS::gc_metadata*)> >("destruct ::FE::internal::ECS::gc_metadata", &::std::destroy_at<::FE::internal::ECS::gc_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::internal::ECS::component_metadata*(::FE::internal::ECS::component_metadata*)> >("construct ::FE::internal::ECS::component_metadata", &::std::construct_at<::FE::internal::ECS::component_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::internal::ECS::component_metadata*)> >("destruct ::FE::internal::ECS::component_metadata", &::std::destroy_at<::FE::internal::ECS::component_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::internal::ECS::gc_metadata_proxy_table*(::FE::internal::ECS::gc_metadata_proxy_table*)> >("construct ::FE::internal::ECS::gc_metadata_proxy_table", &::std::construct_at<::FE::internal::ECS::gc_metadata_proxy_table>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::internal::ECS::gc_metadata_proxy_table*)> >("destruct ::FE::internal::ECS::gc_metadata_proxy_table", &::std::destroy_at<::FE::internal::ECS::gc_metadata_proxy_table>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::type_info*(::FE::framework::reflection::type_info*)> >("construct ::FE::framework::reflection::type_info", &::std::construct_at<::FE::framework::reflection::type_info>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::type_info*)> >("destruct ::FE::framework::reflection::type_info", &::std::destroy_at<::FE::framework::reflection::type_info>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::internal::type_info::metadata*(::FE::framework::reflection::internal::type_info::metadata*)> >("construct ::FE::framework::reflection::internal::type_info::metadata", &::std::construct_at<::FE::framework::reflection::internal::type_info::metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::internal::type_info::metadata*)> >("destruct ::FE::framework::reflection::internal::type_info::metadata", &::std::destroy_at<::FE::framework::reflection::internal::type_info::metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::cpp_style_task<::FE::framework::ECS, ::FE::component_view<::FE::component_base>(::FE::entity<::FE::archetype_base>)> >("::FE::framework::internal::processors::reachability_analysis_arguments", &::FE::framework::ECS::instanciate_component<::FE::framework::internal::processors::reachability_analysis_arguments>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::cpp_style_task<::FE::framework::ECS, void(::FE::entity<::FE::archetype_base>)> >("~::FE::framework::internal::processors::reachability_analysis_arguments", &::FE::framework::ECS::remove_component<::FE::framework::internal::processors::reachability_analysis_arguments>);

    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::std::pmr::string&, ::FE::component_base* const, ::FE::ASCII* const)> >("serialize_component_FE_framework_internal_processors_reachability_analysis_arguments", &serialize_component_FE_framework_internal_processors_reachability_analysis_arguments);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(const ::std::pmr::string&, ::FE::component_base* const, ::FE::ASCII* const)> >("deserialize_component_FE_framework_internal_processors_reachability_analysis_arguments", &deserialize_component_FE_framework_internal_processors_reachability_analysis_arguments);

    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::task*(::FE::framework::task*)> >("construct ::FE::framework::task", &::std::construct_at<::FE::framework::task>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::task*)> >("destruct ::FE::framework::task", &::std::destroy_at<::FE::framework::task>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::internal::processors::fiber_stack_allocator*(::FE::framework::internal::processors::fiber_stack_allocator*)> >("construct ::FE::framework::internal::processors::fiber_stack_allocator", &::std::construct_at<::FE::framework::internal::processors::fiber_stack_allocator>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::internal::processors::fiber_stack_allocator*)> >("destruct ::FE::framework::internal::processors::fiber_stack_allocator", &::std::destroy_at<::FE::framework::internal::processors::fiber_stack_allocator>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::internal::smart_ptr::metadata*(::FE::internal::smart_ptr::metadata*)> >("construct ::FE::internal::smart_ptr::metadata", &::std::construct_at<::FE::internal::smart_ptr::metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::internal::smart_ptr::metadata*)> >("destruct ::FE::internal::smart_ptr::metadata", &::std::destroy_at<::FE::internal::smart_ptr::metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::instance_metadata*(::FE::framework::reflection::instance_metadata*)> >("construct ::FE::framework::reflection::instance_metadata", &::std::construct_at<::FE::framework::reflection::instance_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::instance_metadata*)> >("destruct ::FE::framework::reflection::instance_metadata", &::std::destroy_at<::FE::framework::reflection::instance_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::enum_metadata*(::FE::framework::reflection::enum_metadata*)> >("construct ::FE::framework::reflection::enum_metadata", &::std::construct_at<::FE::framework::reflection::enum_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::enum_metadata*)> >("destruct ::FE::framework::reflection::enum_metadata", &::std::destroy_at<::FE::framework::reflection::enum_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::enum_registry*(::FE::framework::reflection::enum_registry*)> >("construct ::FE::framework::reflection::enum_registry", &::std::construct_at<::FE::framework::reflection::enum_registry>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::enum_registry*)> >("destruct ::FE::framework::reflection::enum_registry", &::std::destroy_at<::FE::framework::reflection::enum_registry>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::property_metadata*(::FE::framework::reflection::property_metadata*)> >("construct ::FE::framework::reflection::property_metadata", &::std::construct_at<::FE::framework::reflection::property_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::property_metadata*)> >("destruct ::FE::framework::reflection::property_metadata", &::std::destroy_at<::FE::framework::reflection::property_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::instance_metadata*(::FE::framework::reflection::instance_metadata*)> >("construct ::FE::framework::reflection::instance_metadata", &::std::construct_at<::FE::framework::reflection::instance_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::instance_metadata*)> >("destruct ::FE::framework::reflection::instance_metadata", &::std::destroy_at<::FE::framework::reflection::instance_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::enum_metadata*(::FE::framework::reflection::enum_metadata*)> >("construct ::FE::framework::reflection::enum_metadata", &::std::construct_at<::FE::framework::reflection::enum_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::enum_metadata*)> >("destruct ::FE::framework::reflection::enum_metadata", &::std::destroy_at<::FE::framework::reflection::enum_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::enum_registry*(::FE::framework::reflection::enum_registry*)> >("construct ::FE::framework::reflection::enum_registry", &::std::construct_at<::FE::framework::reflection::enum_registry>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::enum_registry*)> >("destruct ::FE::framework::reflection::enum_registry", &::std::destroy_at<::FE::framework::reflection::enum_registry>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<::FE::framework::reflection::property_metadata*(::FE::framework::reflection::property_metadata*)> >("construct ::FE::framework::reflection::property_metadata", &::std::construct_at<::FE::framework::reflection::property_metadata>);
    ::FE::framework::framework_base::get_framework().get_method_reflection().register_task< ::FE::c_style_task<void(::FE::framework::reflection::property_metadata*)> >("destruct ::FE::framework::reflection::property_metadata", &::std::destroy_at<::FE::framework::reflection::property_metadata>);
}
