/*
* Test Code is generated by LLM and is reviewed by the maintainer.
* 
Google Test suite for FE::buffer<Allocator>.

Covers:
  - member type aliases and noexcept guarantees
  - default / allocator / sized construction (including zero-fill semantics)
  - copy construction (deep copy, independence, allocator-extended overload)
  - move construction (steal, allocator-extended: equal steals / unequal copies)
  - copy & move assignment (self-assignment, old storage release,
    POCCA / POCMA propagation, equal vs. unequal allocator paths)
  - resize (grow, shrink, same-size no-op, resize-to-zero)
  - lifetime correctness via a tracking allocator (no leaks, no double frees,
    deallocate() always receives the size that allocate() returned)

Build (standalone):
    g++ -std=c++20 -I<engine_include_root> buffer_test.cpp -lgtest -lgtest_main -pthread -o buffer_test

Build (CMake):
    target_link_libraries(fe_buffer_test PRIVATE GTest::gtest_main)

No main() is required when linking against gtest_main.
*/
#include <gtest/gtest.h>

#include <FE/buffer.hxx> // adjust to the header's location in the engine tree

#include <cstddef>
#include <cstring>
#include <memory>
#include <type_traits>
#include <unordered_map>
#include <utility>


namespace
{

// ---------------------------------------------------------------------------
// Test allocator infrastructure
// ---------------------------------------------------------------------------

// Shared bookkeeping for one or more test_allocator instances.
struct allocation_tracker
{
    std::size_t allocate_calls = 0;
    std::size_t deallocate_calls = 0;
    std::unordered_map<void*, std::size_t> live_blocks; // pointer -> allocated size
    bool wrong_size_deallocation = false;
    bool unknown_pointer_deallocation = false;

    bool all_freed() const noexcept
    {
        return live_blocks.empty();
    }

    // No leaks, no double/foreign frees, and every deallocate() size matched allocate().
    bool clean() const noexcept
    {
        return live_blocks.empty() && !wrong_size_deallocation && !unknown_pointer_deallocation;
    }
};

// A stateful char allocator. Equality is defined by m_id, and every
// (de)allocation is recorded in the tracker it was constructed with.
template <bool PropagateOnCopyAssignment, bool PropagateOnMoveAssignment>
class test_allocator
{
public:
    using value_type = char;
    using propagate_on_container_copy_assignment = std::bool_constant<PropagateOnCopyAssignment>;
    using propagate_on_container_move_assignment = std::bool_constant<PropagateOnMoveAssignment>;
    using is_always_equal = std::false_type;

    allocation_tracker* m_tracker;
    int m_id;

    test_allocator() noexcept
        : m_tracker(nullptr)
        , m_id(0)
    {
    }

    explicit test_allocator(allocation_tracker* tracker_p, int id_p = 0) noexcept
        : m_tracker(tracker_p)
        , m_id(id_p)
    {
    }

    char* allocate(std::size_t count_p)
    {
        char* l_pointer = static_cast<char*>(::operator new(count_p));
        if (m_tracker != nullptr)
        {
            ++m_tracker->allocate_calls;
            m_tracker->live_blocks.emplace(l_pointer, count_p);
        }
        return l_pointer;
    }

    void deallocate(char* pointer_p, std::size_t count_p) noexcept
    {
        if (m_tracker != nullptr)
        {
            ++m_tracker->deallocate_calls;
            auto l_iterator = m_tracker->live_blocks.find(pointer_p);
            if (l_iterator == m_tracker->live_blocks.end())
            {
                m_tracker->unknown_pointer_deallocation = true;
            }
            else
            {
                if (l_iterator->second != count_p)
                {
                    m_tracker->wrong_size_deallocation = true;
                }
                m_tracker->live_blocks.erase(l_iterator);
            }
        }
        ::operator delete(pointer_p);
    }

    bool operator==(const test_allocator& other_p) const noexcept
    {
        return m_id == other_p.m_id;
    }

    bool operator!=(const test_allocator& other_p) const noexcept
    {
        return m_id != other_p.m_id;
    }
};

using plain_allocator      = test_allocator<false, false>; // no propagation
using pocca_allocator      = test_allocator<true, false>;  // propagates on copy assignment
using pocma_allocator      = test_allocator<false, true>;  // propagates on move assignment


// ---------------------------------------------------------------------------
// Content helpers
// ---------------------------------------------------------------------------

constexpr unsigned char default_seed = 0x40;

template <class Buffer>
void fill_pattern(Buffer& buffer_p, unsigned char seed_p = default_seed) noexcept
{
    for (std::size_t i = 0; i < buffer_p.size(); ++i)
    {
        buffer_p.data()[i] = static_cast<char>((seed_p + i) & 0xFFu);
    }
}

template <class Buffer>
::testing::AssertionResult matches_pattern(const Buffer& buffer_p, std::size_t count_p, unsigned char seed_p = default_seed)
{
    for (std::size_t i = 0; i < count_p; ++i)
    {
        const char l_expected = static_cast<char>((seed_p + i) & 0xFFu);
        if (buffer_p.data()[i] != l_expected)
        {
            return ::testing::AssertionFailure()
                   << "byte " << i << " is " << static_cast<int>(buffer_p.data()[i])
                   << ", expected " << static_cast<int>(l_expected);
        }
    }
    return ::testing::AssertionSuccess();
}

template <class Buffer>
::testing::AssertionResult is_zero_filled(const Buffer& buffer_p, std::size_t begin_p, std::size_t end_p)
{
    for (std::size_t i = begin_p; i < end_p; ++i)
    {
        if (buffer_p.data()[i] != 0)
        {
            return ::testing::AssertionFailure() << "non-zero byte at index " << i;
        }
    }
    return ::testing::AssertionSuccess();
}


// ---------------------------------------------------------------------------
// Member types and noexcept guarantees
// ---------------------------------------------------------------------------


TEST(BufferTraits, NoexceptGuarantees)
{
    using buffer_t = FE::buffer<>;
    static_assert(std::is_nothrow_default_constructible_v<buffer_t>);
    static_assert(std::is_nothrow_copy_constructible_v<buffer_t>);
    static_assert(std::is_nothrow_move_constructible_v<buffer_t>);
    static_assert(std::is_nothrow_copy_assignable_v<buffer_t>);
    static_assert(std::is_nothrow_move_assignable_v<buffer_t>);
    static_assert(std::is_nothrow_destructible_v<buffer_t>);
    SUCCEED();
}


// ---------------------------------------------------------------------------
// Construction
// ---------------------------------------------------------------------------

TEST(BufferConstruction, DefaultConstructedIsEmpty)
{
    FE::buffer<> l_buffer;

    EXPECT_EQ(l_buffer.data(), nullptr);
    EXPECT_EQ(l_buffer.size(), 0u);
}

TEST(BufferConstruction, AllocatorConstructedIsEmptyAndDoesNotAllocate)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_buffer(l_alloc);

        EXPECT_EQ(l_buffer.data(), nullptr);
        EXPECT_EQ(l_buffer.size(), 0u);
        EXPECT_EQ(l_tracker.allocate_calls, 0u);
    }
    EXPECT_EQ(l_tracker.deallocate_calls, 0u);
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferConstruction, SizedConstructionAllocatesZeroFilledStorage)
{
    constexpr std::size_t l_count = 64;
    FE::buffer<> l_buffer(l_count);

    ASSERT_NE(l_buffer.data(), nullptr);
    EXPECT_EQ(l_buffer.size(), l_count);
    EXPECT_TRUE(is_zero_filled(l_buffer, 0, l_count));
}

TEST(BufferConstruction, SizedConstructionWithZeroCountStaysEmpty)
{
    FE::buffer<> l_buffer(0);

    EXPECT_EQ(l_buffer.data(), nullptr);
    EXPECT_EQ(l_buffer.size(), 0u);
}


// ---------------------------------------------------------------------------
// data() / size() accessors
// ---------------------------------------------------------------------------

TEST(BufferAccessors, DataIsWritableAndReadable)
{
    FE::buffer<> l_buffer(8);
    std::memcpy(l_buffer.data(), "abcdefg", 8); // 7 chars + '\0'

    EXPECT_STREQ(l_buffer.data(), "abcdefg");
}

TEST(BufferAccessors, ConstOverloadReturnsPointerToConstSameStorage)
{
    FE::buffer<> l_buffer(4);
    const FE::buffer<>& l_const_reference = l_buffer;

    static_assert(std::is_same_v<decltype(l_buffer.data()), char*>);
    static_assert(std::is_same_v<decltype(l_const_reference.data()), const char*>);
    EXPECT_EQ(l_const_reference.data(), l_buffer.data());
    EXPECT_EQ(l_const_reference.size(), l_buffer.size());
}


// ---------------------------------------------------------------------------
// Copy construction
// ---------------------------------------------------------------------------

TEST(BufferCopy, CopyConstructorDeepCopiesContents)
{
    FE::buffer<> l_source(32);
    fill_pattern(l_source);

    FE::buffer<> l_copy(l_source);

    ASSERT_EQ(l_copy.size(), l_source.size());
    ASSERT_NE(l_copy.data(), nullptr);
    EXPECT_NE(l_copy.data(), l_source.data());
    EXPECT_TRUE(matches_pattern(l_copy, l_copy.size()));
    EXPECT_TRUE(matches_pattern(l_source, l_source.size())); // source untouched
}

TEST(BufferCopy, CopyIsIndependentOfSource)
{
    FE::buffer<> l_source(16);
    fill_pattern(l_source);

    FE::buffer<> l_copy(l_source);
    std::memset(l_copy.data(), 0x7F, l_copy.size());

    EXPECT_TRUE(matches_pattern(l_source, l_source.size()));
}

TEST(BufferCopy, CopyConstructorOfEmptyBufferIsEmpty)
{
    FE::buffer<> l_source;

    FE::buffer<> l_copy(l_source);

    EXPECT_EQ(l_copy.data(), nullptr);
    EXPECT_EQ(l_copy.size(), 0u);
}

TEST(BufferCopy, CopyConstructorUsesCopyOfSourceAllocator)
{
    // select_on_container_copy_construction defaults to returning a copy of the
    // source allocator, so the copy's allocation must land in the same tracker.
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_source(16, l_alloc);
        FE::buffer<plain_allocator> l_copy(l_source);

        EXPECT_EQ(l_tracker.allocate_calls, 2u);
    }
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferCopy, AllocatorExtendedCopyConstructorUsesProvidedAllocator)
{
    allocation_tracker l_tracker_a;
    allocation_tracker l_tracker_b;
    plain_allocator l_alloc_a(&l_tracker_a, 1);
    plain_allocator l_alloc_b(&l_tracker_b, 2);

    {
        FE::buffer<plain_allocator> l_source(24, l_alloc_a);
        fill_pattern(l_source);

        FE::buffer<plain_allocator> l_copy(l_source, l_alloc_b);

        EXPECT_EQ(l_copy.size(), 24u);
        EXPECT_TRUE(matches_pattern(l_copy, 24));
        EXPECT_EQ(l_tracker_a.allocate_calls, 1u); // only the source's storage
        EXPECT_EQ(l_tracker_b.allocate_calls, 1u); // the copy went through alloc B
    }
    EXPECT_TRUE(l_tracker_a.clean());
    EXPECT_TRUE(l_tracker_b.clean());
}


// ---------------------------------------------------------------------------
// Move construction
// ---------------------------------------------------------------------------

TEST(BufferMove, MoveConstructorStealsStorageAndEmptiesSource)
{
    FE::buffer<> l_source(32);
    fill_pattern(l_source);
    char* const l_original_pointer = l_source.data();

    FE::buffer<> l_moved(std::move(l_source));

    EXPECT_EQ(l_moved.data(), l_original_pointer);
    EXPECT_EQ(l_moved.size(), 32u);
    EXPECT_TRUE(matches_pattern(l_moved, 32));
    EXPECT_EQ(l_source.data(), nullptr);
    EXPECT_EQ(l_source.size(), 0u);
}

TEST(BufferMove, MoveConstructorOfEmptyBufferIsEmpty)
{
    FE::buffer<> l_source;

    FE::buffer<> l_moved(std::move(l_source));

    EXPECT_EQ(l_moved.data(), nullptr);
    EXPECT_EQ(l_moved.size(), 0u);
}

TEST(BufferMove, MovedFromBufferIsReusable)
{
    FE::buffer<> l_source(16);
    FE::buffer<> l_moved(std::move(l_source));

    l_source.resize(8);

    ASSERT_NE(l_source.data(), nullptr);
    EXPECT_EQ(l_source.size(), 8u);
    EXPECT_TRUE(is_zero_filled(l_source, 0, 8));
}

TEST(BufferMove, AllocatorExtendedMoveWithEqualAllocatorSteals)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc_first(&l_tracker, 7);
    plain_allocator l_alloc_second(&l_tracker, 7); // same id -> allocators compare equal

    {
        FE::buffer<plain_allocator> l_source(16, l_alloc_first);
        char* const l_original_pointer = l_source.data();

        FE::buffer<plain_allocator> l_moved(std::move(l_source), l_alloc_second);

        EXPECT_EQ(l_moved.data(), l_original_pointer);
        EXPECT_EQ(l_moved.size(), 16u);
        EXPECT_EQ(l_source.data(), nullptr);
        EXPECT_EQ(l_source.size(), 0u);
        EXPECT_EQ(l_tracker.allocate_calls, 1u); // no extra allocation happened
    }
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferMove, AllocatorExtendedMoveWithUnequalAllocatorCopies)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc_first(&l_tracker, 1);
    plain_allocator l_alloc_second(&l_tracker, 2); // different id -> unequal

    {
        FE::buffer<plain_allocator> l_source(16, l_alloc_first);
        fill_pattern(l_source);
        char* const l_original_pointer = l_source.data();

        FE::buffer<plain_allocator> l_moved(std::move(l_source), l_alloc_second);

        EXPECT_NE(l_moved.data(), l_original_pointer);
        EXPECT_EQ(l_moved.size(), 16u);
        EXPECT_TRUE(matches_pattern(l_moved, 16));
        // Current implementation leaves the source's storage intact on this path.
        EXPECT_EQ(l_source.data(), l_original_pointer);
        EXPECT_EQ(l_source.size(), 16u);
        EXPECT_EQ(l_tracker.allocate_calls, 2u);
    }
    EXPECT_TRUE(l_tracker.clean());
}


// ---------------------------------------------------------------------------
// Copy assignment
// ---------------------------------------------------------------------------

TEST(BufferAssignment, CopyAssignmentDeepCopies)
{
    FE::buffer<> l_source(20);
    fill_pattern(l_source);

    FE::buffer<> l_destination(5);
    l_destination = l_source;

    ASSERT_EQ(l_destination.size(), 20u);
    EXPECT_NE(l_destination.data(), l_source.data());
    EXPECT_TRUE(matches_pattern(l_destination, 20));
    EXPECT_TRUE(matches_pattern(l_source, 20));
}

TEST(BufferAssignment, CopyAssignmentReleasesPreviousStorage)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_destination(64, l_alloc);
        FE::buffer<plain_allocator> l_source(8, l_alloc);
        fill_pattern(l_source);

        l_destination = l_source;

        EXPECT_EQ(l_destination.size(), 8u);
        EXPECT_TRUE(matches_pattern(l_destination, 8));
        EXPECT_EQ(l_tracker.deallocate_calls, 1u); // the old 64-byte block
        EXPECT_FALSE(l_tracker.wrong_size_deallocation);
    }
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferAssignment, CopyAssignmentFromEmptyMakesDestinationEmpty)
{
    FE::buffer<> l_destination(12);
    FE::buffer<> l_source;

    l_destination = l_source;

    EXPECT_EQ(l_destination.data(), nullptr);
    EXPECT_EQ(l_destination.size(), 0u);
}

TEST(BufferAssignment, SelfCopyAssignmentIsNoOp)
{
    FE::buffer<> l_buffer(10);
    fill_pattern(l_buffer);
    char* const l_original_pointer = l_buffer.data();

    FE::buffer<>& l_self = l_buffer; // avoids compiler self-assignment warnings
    l_buffer = l_self;

    EXPECT_EQ(l_buffer.data(), l_original_pointer);
    EXPECT_EQ(l_buffer.size(), 10u);
    EXPECT_TRUE(matches_pattern(l_buffer, 10));
}


// ---------------------------------------------------------------------------
// Move assignment
// ---------------------------------------------------------------------------

TEST(BufferAssignment, MoveAssignmentStealsStorageAndEmptiesSource)
{
    FE::buffer<> l_source(24);
    fill_pattern(l_source);
    char* const l_original_pointer = l_source.data();

    FE::buffer<> l_destination(4);
    l_destination = std::move(l_source);

    EXPECT_EQ(l_destination.data(), l_original_pointer);
    EXPECT_EQ(l_destination.size(), 24u);
    EXPECT_TRUE(matches_pattern(l_destination, 24));
    EXPECT_EQ(l_source.data(), nullptr);
    EXPECT_EQ(l_source.size(), 0u);
}

TEST(BufferAssignment, MoveAssignmentFromEmptySourceEmptiesDestination)
{
    FE::buffer<> l_destination(12);
    FE::buffer<> l_source;

    l_destination = std::move(l_source);

    EXPECT_EQ(l_destination.data(), nullptr);
    EXPECT_EQ(l_destination.size(), 0u);
}

TEST(BufferAssignment, SelfMoveAssignmentIsNoOp)
{
    FE::buffer<> l_buffer(10);
    fill_pattern(l_buffer);
    char* const l_original_pointer = l_buffer.data();

    FE::buffer<>& l_self = l_buffer; // avoids compiler self-move warnings
    l_buffer = std::move(l_self);

    EXPECT_EQ(l_buffer.data(), l_original_pointer);
    EXPECT_EQ(l_buffer.size(), 10u);
    EXPECT_TRUE(matches_pattern(l_buffer, 10));
}


// ---------------------------------------------------------------------------
// Allocator propagation (POCCA / POCMA)
// ---------------------------------------------------------------------------

TEST(BufferAllocatorPropagation, CopyAssignmentPropagatesAllocatorWhenPoccaTrue)
{
    allocation_tracker l_tracker_a;
    allocation_tracker l_tracker_b;
    pocca_allocator l_alloc_a(&l_tracker_a, 1);
    pocca_allocator l_alloc_b(&l_tracker_b, 2);

    {
        FE::buffer<pocca_allocator> l_destination(8, l_alloc_a);
        FE::buffer<pocca_allocator> l_source(16, l_alloc_b);

        l_destination = l_source;

        // The old block is released through the destination's original allocator...
        EXPECT_EQ(l_tracker_a.deallocate_calls, 1u);
        EXPECT_TRUE(l_tracker_a.all_freed());
        // ...and the new block is acquired through the propagated allocator.
        EXPECT_EQ(l_tracker_b.allocate_calls, 2u);
    }
    EXPECT_TRUE(l_tracker_a.clean());
    EXPECT_TRUE(l_tracker_b.clean());
}

TEST(BufferAllocatorPropagation, CopyAssignmentKeepsOwnAllocatorWhenPoccaFalse)
{
    allocation_tracker l_tracker_a;
    allocation_tracker l_tracker_b;
    plain_allocator l_alloc_a(&l_tracker_a, 1);
    plain_allocator l_alloc_b(&l_tracker_b, 2);

    {
        FE::buffer<plain_allocator> l_destination(8, l_alloc_a);
        FE::buffer<plain_allocator> l_source(16, l_alloc_b);

        l_destination = l_source;

        // Both the release of the old block and the new allocation stay on tracker A.
        EXPECT_EQ(l_tracker_a.deallocate_calls, 1u);
        EXPECT_EQ(l_tracker_a.allocate_calls, 2u);
        EXPECT_EQ(l_tracker_b.allocate_calls, 1u); // only the source's own storage
    }
    EXPECT_TRUE(l_tracker_a.clean());
    EXPECT_TRUE(l_tracker_b.clean());
}

TEST(BufferAllocatorPropagation, MoveAssignmentStealsAcrossUnequalAllocatorsWhenPocmaTrue)
{
    allocation_tracker l_tracker_a;
    allocation_tracker l_tracker_b;
    pocma_allocator l_alloc_a(&l_tracker_a, 1);
    pocma_allocator l_alloc_b(&l_tracker_b, 2);

    {
        FE::buffer<pocma_allocator> l_destination(8, l_alloc_a);
        FE::buffer<pocma_allocator> l_source(16, l_alloc_b);
        fill_pattern(l_source);
        char* const l_original_pointer = l_source.data();

        l_destination = std::move(l_source);

        EXPECT_EQ(l_destination.data(), l_original_pointer); // stolen, not copied
        EXPECT_EQ(l_destination.size(), 16u);
        EXPECT_TRUE(matches_pattern(l_destination, 16));
        EXPECT_EQ(l_source.data(), nullptr);
        EXPECT_EQ(l_source.size(), 0u);
        EXPECT_EQ(l_tracker_a.deallocate_calls, 1u); // old block freed via old allocator
        EXPECT_EQ(l_tracker_b.allocate_calls, 1u);   // no extra allocation happened
    }
    // The stolen block must be released through the propagated allocator (tracker B),
    // with the size it was originally allocated with.
    EXPECT_TRUE(l_tracker_a.clean());
    EXPECT_TRUE(l_tracker_b.clean());
}

TEST(BufferAllocatorPropagation, MoveAssignmentWithEqualAllocatorsStealsWhenPocmaFalse)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc_first(&l_tracker, 3);
    plain_allocator l_alloc_second(&l_tracker, 3); // equal

    {
        FE::buffer<plain_allocator> l_destination(8, l_alloc_first);
        FE::buffer<plain_allocator> l_source(16, l_alloc_second);
        char* const l_original_pointer = l_source.data();

        l_destination = std::move(l_source);

        EXPECT_EQ(l_destination.data(), l_original_pointer);
        EXPECT_EQ(l_destination.size(), 16u);
        EXPECT_EQ(l_source.data(), nullptr);
        EXPECT_EQ(l_tracker.allocate_calls, 2u); // the move itself allocated nothing
    }
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferAllocatorPropagation, MoveAssignmentWithUnequalAllocatorsCopiesWhenPocmaFalse)
{
    allocation_tracker l_tracker_a;
    allocation_tracker l_tracker_b;
    plain_allocator l_alloc_a(&l_tracker_a, 1);
    plain_allocator l_alloc_b(&l_tracker_b, 2);

    {
        FE::buffer<plain_allocator> l_destination(8, l_alloc_a);
        FE::buffer<plain_allocator> l_source(16, l_alloc_b);
        fill_pattern(l_source);
        char* const l_original_pointer = l_source.data();

        l_destination = std::move(l_source);

        EXPECT_NE(l_destination.data(), l_original_pointer); // copied, not stolen
        EXPECT_EQ(l_destination.size(), 16u);
        EXPECT_TRUE(matches_pattern(l_destination, 16));
        // Current implementation leaves the source's storage intact on this path.
        EXPECT_EQ(l_source.data(), l_original_pointer);
        EXPECT_EQ(l_source.size(), 16u);
        EXPECT_EQ(l_tracker_a.allocate_calls, 2u); // copy made via destination's allocator
    }
    EXPECT_TRUE(l_tracker_a.clean());
    EXPECT_TRUE(l_tracker_b.clean());
}


// ---------------------------------------------------------------------------
// resize()
// ---------------------------------------------------------------------------

TEST(BufferResize, GrowFromEmptyZeroFills)
{
    FE::buffer<> l_buffer;

    l_buffer.resize(48);

    ASSERT_NE(l_buffer.data(), nullptr);
    EXPECT_EQ(l_buffer.size(), 48u);
    EXPECT_TRUE(is_zero_filled(l_buffer, 0, 48));
}

TEST(BufferResize, GrowPreservesContentAndZeroFillsTail)
{
    FE::buffer<> l_buffer(16);
    fill_pattern(l_buffer);

    l_buffer.resize(40);

    ASSERT_EQ(l_buffer.size(), 40u);
    EXPECT_TRUE(matches_pattern(l_buffer, 16));   // original prefix preserved
    EXPECT_TRUE(is_zero_filled(l_buffer, 16, 40)); // new tail zeroed
}

TEST(BufferResize, ShrinkPreservesPrefix)
{
    FE::buffer<> l_buffer(32);
    fill_pattern(l_buffer);

    l_buffer.resize(10);

    ASSERT_EQ(l_buffer.size(), 10u);
    ASSERT_NE(l_buffer.data(), nullptr);
    EXPECT_TRUE(matches_pattern(l_buffer, 10));
}

TEST(BufferResize, ResizeToZeroReleasesStorage)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    FE::buffer<plain_allocator> l_buffer(32, l_alloc);
    l_buffer.resize(0);

    EXPECT_EQ(l_buffer.data(), nullptr);
    EXPECT_EQ(l_buffer.size(), 0u);
    EXPECT_TRUE(l_tracker.clean()); // block freed with the matching size
}

TEST(BufferResize, ResizeToSameSizeIsNoOp)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    FE::buffer<plain_allocator> l_buffer(16, l_alloc);
    fill_pattern(l_buffer);
    char* const l_original_pointer = l_buffer.data();

    l_buffer.resize(16);

    EXPECT_EQ(l_buffer.data(), l_original_pointer); // early-out, no reallocation
    EXPECT_EQ(l_buffer.size(), 16u);
    EXPECT_TRUE(matches_pattern(l_buffer, 16));
    EXPECT_EQ(l_tracker.allocate_calls, 1u);
}

TEST(BufferResize, RepeatedResizeNeverLeaksOrMismatchesSizes)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_buffer(1, l_alloc);
        const std::size_t l_sizes[] = { 5, 100, 3, 3, 250, 0, 7 };

        for (std::size_t l_count : l_sizes)
        {
            l_buffer.resize(l_count);
            EXPECT_EQ(l_buffer.size(), l_count);
        }
    }
    EXPECT_TRUE(l_tracker.clean());
    EXPECT_EQ(l_tracker.allocate_calls, l_tracker.deallocate_calls);
}


// ---------------------------------------------------------------------------
// Lifetime / destructor
// ---------------------------------------------------------------------------

TEST(BufferLifetime, DestructorReleasesStorageWithMatchingSize)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_buffer(128, l_alloc);
        EXPECT_EQ(l_tracker.allocate_calls, 1u);
    }
    EXPECT_EQ(l_tracker.deallocate_calls, 1u);
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferLifetime, DestructorOfEmptyBufferDoesNotDeallocate)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_buffer(l_alloc);
    }
    EXPECT_EQ(l_tracker.deallocate_calls, 0u);
    EXPECT_TRUE(l_tracker.clean());
}

TEST(BufferLifetime, MovedFromBufferDestructsWithoutDoubleFree)
{
    allocation_tracker l_tracker;
    plain_allocator l_alloc(&l_tracker, 1);

    {
        FE::buffer<plain_allocator> l_source(32, l_alloc);
        FE::buffer<plain_allocator> l_moved(std::move(l_source));
        // Both go out of scope here; exactly one deallocation must occur.
    }
    EXPECT_EQ(l_tracker.allocate_calls, 1u);
    EXPECT_EQ(l_tracker.deallocate_calls, 1u);
    EXPECT_TRUE(l_tracker.clean());
}

} // anonymous namespace