// Test code is generated by Claude, and it is maintained and reviewed by UNKNOWN STRYKER (Joey 'Hojin' Lee)
#pragma warning (disable: 4067) // disable warning C4067: unexpected tokens following preprocessor directive - expected a newline
#include <gtest/gtest.h>
#include <benchmark/benchmark.h>

// std
#include <iostream>
#include <string>
#include <random>

// Copyright © from 2023 to current, UNKNOWN STRYKER (Hojin Lee / Joey). All Rights Reserved.
#include <FE/algorithm/utility.hxx>
#include <FE/memory_resource.hxx>
#include <FE/framework.hxx>

#include <FE/concurrent_memory_resource.hxx>

// oneTBB is optional.
// FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE is normally set by CMake, which is the only place that knows whether
// tbbmalloc actually reached the link line. The __has_include fallback below is for builds that do not set it, and
// it can only prove that the header exists, not that the library is linked - a header only check is what produced
// the unresolved scalable_aligned_malloc / scalable_free at link time.
// NOTE: "#ifdef __has_include( <header> )" is always taken. #ifdef tests whether the identifier __has_include is
// defined, which it always is in C++17 and later, and the parenthesised header name is discarded as extra tokens.
// The functional form "#if __has_include(<header>)" is the one that tests for the header.
#ifndef FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
#if __has_include(<tbb/scalable_allocator.h>)
#define FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE 1
#else
#define FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE 0
#endif
#endif

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
#include <tbb/scalable_allocator.h>
// __TBB_CPP17_MEMORY_RESOURCE_PRESENT is TBB's own guard around tbb::scalable_memory_resource, and the header is
// what defines it, so it can only be tested after the include. It vetoes the rows even when the build system
// asked for them.
#if !__TBB_CPP17_MEMORY_RESOURCE_PRESENT
#undef FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
#define FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE 0
#endif
#endif




void new_delete_extreme_fixed_sized_accumulation_test(benchmark::State& state_p) noexcept
{
	std::list<std::string> l_strings;
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}
BENCHMARK(new_delete_extreme_fixed_sized_accumulation_test)->Iterations(1000);

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_extreme_fixed_sized_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(tbb::scalable_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}
BENCHMARK(tbb_scalable_memory_resource_extreme_fixed_sized_accumulation_test)->Iterations(1000);
#endif

void std_pmr_unsynchronized_pool_resource_extreme_fixed_sized_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::unsynchronized_pool_resource l_resource;
	benchmark::DoNotOptimize(l_resource);

	std::pmr::list<std::string> l_strings(&l_resource);
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}
BENCHMARK(std_pmr_unsynchronized_pool_resource_extreme_fixed_sized_accumulation_test)->Iterations(1000);


void FE_TLGPM_extreme_fixed_sized_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(FE::framework::framework_base::get_framework().get_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}
BENCHMARK(FE_TLGPM_extreme_fixed_sized_accumulation_test)->Iterations(1000);

void FE_LTLGPM_extreme_fixed_sized_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(FE::framework::framework_base::get_framework().get_large_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}
BENCHMARK(FE_LTLGPM_extreme_fixed_sized_accumulation_test)->Iterations(1000);




void new_delete_extreme_fixed_sized_test(benchmark::State& state_p) noexcept
{
	std::list<std::string> l_strings;
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}
BENCHMARK(new_delete_extreme_fixed_sized_test)->Iterations(30000);

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_extreme_fixed_sized_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(tbb::scalable_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}
BENCHMARK(tbb_scalable_memory_resource_extreme_fixed_sized_test)->Iterations(30000);
#endif

void std_pmr_unsynchronized_pool_resource_extreme_fixed_sized_test(benchmark::State& state_p) noexcept
{
	std::pmr::unsynchronized_pool_resource l_resource;
	benchmark::DoNotOptimize(l_resource);

	std::pmr::list<std::string> l_strings(&l_resource);
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}
BENCHMARK(std_pmr_unsynchronized_pool_resource_extreme_fixed_sized_test)->Iterations(30000);


void FE_TLGPM_extreme_fixed_sized_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(FE::framework::framework_base::get_framework().get_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}
BENCHMARK(FE_TLGPM_extreme_fixed_sized_test)->Iterations(30000);

void FE_LTLGPM_extreme_fixed_sized_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(FE::framework::framework_base::get_framework().get_large_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}
BENCHMARK(FE_LTLGPM_extreme_fixed_sized_test)->Iterations(30000);




// ---------------------------------------------------------------------------------------------------------------------
// Random-size benchmarks.
// The size stream is deterministic and shared: every allocator variant draws the same sizes in the same order.
// rand() is not used because MSVC's RAND_MAX is 32767, so "rand() % (4 MiB)" never produced a size above 32767.
// reserve() is used instead of resize() so that the measurement is the allocation itself, not the zero-fill of the block.
// ---------------------------------------------------------------------------------------------------------------------
class random_size_sequence
{
	std::mt19937 m_engine;
	std::uniform_int_distribution<var::int32> m_distribution;
	static constexpr std::uint32_t seed = 20260903u;

public:
	random_size_sequence(FE::int32 min_p, FE::int32 max_p) noexcept : m_engine(seed), m_distribution(min_p, max_p) {}
	void reset() noexcept { m_engine.seed(seed); }
	FE::int32 next() noexcept { return m_distribution(m_engine); }
};
constexpr FE::int32 random_size_min = 1;
constexpr FE::int32 random_size_max = 64 * FE::one_KiB; // <= 128 B goes to the block pools, 129 B ~ 64 KiB to the scalable pool.

// Random size allocation and deallocation benchmark for default C++ operators
void new_delete_random_size_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::vector<std::byte> l_vector;
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}
BENCHMARK(new_delete_random_size_test)->Iterations(10000);

// Random size allocation and deallocation benchmark for tbb::scalable_memory_resource
#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_random_size_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::pmr::vector<std::byte> l_vector(tbb::scalable_memory_resource());
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}
BENCHMARK(tbb_scalable_memory_resource_random_size_test)->Iterations(10000);
#endif


void FE_TLGPM_random_size_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::pmr::vector<std::byte> l_vector(FE::framework::framework_base::get_framework().get_memory_resource());
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}
BENCHMARK(FE_TLGPM_random_size_test)->Iterations(10000);

void FE_LTLGPM_random_size_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::pmr::vector<std::byte> l_vector(FE::framework::framework_base::get_framework().get_large_memory_resource());
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}
BENCHMARK(FE_LTLGPM_random_size_test)->Iterations(10000);




// Random size allocation and deallocation benchmark for default C++ operators
void new_delete_random_size_accumulation_test(benchmark::State& state_p) noexcept
{
	std::vector< std::vector<std::byte> > l_vector;
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset(); // every iteration replays the same 1000 sizes
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::vector<std::byte> l_temp_vector;
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}
BENCHMARK(new_delete_random_size_accumulation_test)->Iterations(1000);

// Random size allocation and deallocation benchmark for tbb::scalable_memory_resource
#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_random_size_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::vector< std::pmr::vector<std::byte> > l_vector(tbb::scalable_memory_resource());
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::pmr::vector<std::byte> l_temp_vector(tbb::scalable_memory_resource());
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}
BENCHMARK(tbb_scalable_memory_resource_random_size_accumulation_test)->Iterations(1000);
#endif


void FE_TLGPM_random_size_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::vector< std::pmr::vector<std::byte> > l_vector(FE::framework::framework_base::get_framework().get_memory_resource());
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::pmr::vector<std::byte> l_temp_vector(FE::framework::framework_base::get_framework().get_memory_resource());
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}
BENCHMARK(FE_TLGPM_random_size_accumulation_test)->Iterations(1000);

void FE_LTLGPM_random_size_accumulation_test(benchmark::State& state_p) noexcept
{
	std::pmr::vector< std::pmr::vector<std::byte> > l_vector(FE::framework::framework_base::get_framework().get_large_memory_resource());
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::pmr::vector<std::byte> l_temp_vector(FE::framework::framework_base::get_framework().get_large_memory_resource());
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}
BENCHMARK(FE_LTLGPM_random_size_accumulation_test)->Iterations(1000);








// ---------------------------------------------------------------------------------------------------------------------
// Concurrent benchmarks.
namespace
{
	FE::concurrent_memory_resource* g_concurrent_memory_resource = nullptr;
	std::pmr::synchronized_pool_resource* g_synchronized_pool_resource = nullptr;

	// This reads the framework, so it must NOT run during static initialization. That is why the benchmarks below
	// are registered from register_concurrent_benchmarks() at the bottom of this file instead of by the BENCHMARK
	// macro: the macro expands to a global scope static whose initializer runs before main(), at which point the
	// framework does not exist yet.
	int max_concurrency() noexcept
	{
		return static_cast<int>(FE::framework::framework_base::get_framework().get_program_options().get_max_concurrency());
	}

	void setup_concurrent_memory_resource(const benchmark::State&)
	{
		const auto& options = FE::framework::framework_base::get_framework().get_program_options();
		g_concurrent_memory_resource = new FE::concurrent_memory_resource(options.is_large_page_enabled(), options.get_max_concurrency());
	}

	void teardown_concurrent_memory_resource(const benchmark::State&)
	{
		delete g_concurrent_memory_resource;
		g_concurrent_memory_resource = nullptr;
	}

	void setup_synchronized_pool_resource(const benchmark::State&)
	{
		g_synchronized_pool_resource = new std::pmr::synchronized_pool_resource();
	}

	void teardown_synchronized_pool_resource(const benchmark::State&)
	{
		delete g_synchronized_pool_resource;
		g_synchronized_pool_resource = nullptr;
	}
}


void new_delete_extreme_fixed_sized_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::list<std::string> l_strings;
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
// No Setup / Teardown pair: tbb::scalable_memory_resource() is a function local static, so every thread already
// shares the one instance this section requires.
void tbb_scalable_memory_resource_extreme_fixed_sized_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(tbb::scalable_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}
#endif

void std_pmr_synchronized_pool_resource_extreme_fixed_sized_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(g_synchronized_pool_resource);
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}


void FE_CMR_extreme_fixed_sized_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(g_concurrent_memory_resource);
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		for (int i = 0; i < 500; ++i)
		{
			l_strings.push_back(std::string());
		}

		for (int i = 0; i < 500; ++i)
		{
			l_strings.pop_back();
		}
	}
}


void new_delete_extreme_fixed_sized_concurrent_test(benchmark::State& state_p) noexcept
{
	std::list<std::string> l_strings;
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_extreme_fixed_sized_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(tbb::scalable_memory_resource());
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}
#endif

void std_pmr_synchronized_pool_resource_extreme_fixed_sized_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(g_synchronized_pool_resource);
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}


void FE_CMR_extreme_fixed_sized_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::list<std::string> l_strings(g_concurrent_memory_resource);
	benchmark::DoNotOptimize(l_strings);
	benchmark::ClobberMemory();

	for (auto _ : state_p)
	{
		l_strings.push_back(std::string());
		l_strings.pop_back();
	}
}


void new_delete_random_size_concurrent_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::vector<std::byte> l_vector;
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_random_size_concurrent_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::pmr::vector<std::byte> l_vector(tbb::scalable_memory_resource());
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}
#endif

void std_pmr_synchronized_pool_resource_random_size_concurrent_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::pmr::vector<std::byte> l_vector(g_synchronized_pool_resource);
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}


void FE_CMR_random_size_concurrent_test(benchmark::State& state_p) noexcept
{
	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		std::pmr::vector<std::byte> l_vector(g_concurrent_memory_resource);
		benchmark::DoNotOptimize(l_vector);
		benchmark::ClobberMemory();

		l_vector.reserve(l_sizes.next());
		benchmark::DoNotOptimize(l_vector.data());
	}
}


void new_delete_random_size_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::vector< std::vector<std::byte> > l_vector;
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::vector<std::byte> l_temp_vector;
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
void tbb_scalable_memory_resource_random_size_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::vector< std::pmr::vector<std::byte> > l_vector(tbb::scalable_memory_resource());
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::pmr::vector<std::byte> l_temp_vector(tbb::scalable_memory_resource());
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}
#endif

void std_pmr_synchronized_pool_resource_random_size_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::vector< std::pmr::vector<std::byte> > l_vector(g_synchronized_pool_resource);
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::pmr::vector<std::byte> l_temp_vector(g_synchronized_pool_resource);
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}


void FE_CMR_random_size_accumulation_concurrent_test(benchmark::State& state_p) noexcept
{
	std::pmr::vector< std::pmr::vector<std::byte> > l_vector(g_concurrent_memory_resource);
	benchmark::DoNotOptimize(l_vector);
	l_vector.reserve(state_p.max_iterations);
	benchmark::ClobberMemory();

	random_size_sequence l_sizes(random_size_min, random_size_max);
	for (auto _ : state_p)
	{
		l_sizes.reset();
		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			std::pmr::vector<std::byte> l_temp_vector(g_concurrent_memory_resource);
			l_temp_vector.reserve(l_sizes.next());
			benchmark::DoNotOptimize(l_temp_vector.data());
			l_vector.emplace_back(std::move(l_temp_vector));
		}

		for (int i = 0; i < state_p.max_iterations; ++i)
		{
			l_vector.pop_back();
		}
	}
}



// ---------------------------------------------------------------------------------------------------------------------
// Runtime registration of everything above.
//
// BENCHMARK(x) expands to a global scope static, so its decorator arguments are evaluated during static
// initialization, before main(). ThreadRange(1, max_concurrency()) therefore reached into the framework before the
// framework was constructed. benchmark::RegisterBenchmark does the same job from ordinary code, so this function
// has to be called AFTER the framework is initialized and BEFORE benchmark::RunSpecifiedBenchmarks().
//
// The single threaded benchmarks earlier in the file keep their BENCHMARK macros: they touch the framework only
// inside their bodies, which run at benchmark time, not at registration time.
// ---------------------------------------------------------------------------------------------------------------------

// The reported names have to stay identical to the ones BENCHMARK(x) produced, so the name comes from the same
// stringised identifier rather than from a hand written string.
#define FE_REGISTER_CONCURRENT_BENCHMARK(function_p) benchmark::RegisterBenchmark(#function_p, function_p)

void register_concurrent_benchmarks() noexcept
{
	const int l_max_threads = max_concurrency();


	FE_REGISTER_CONCURRENT_BENCHMARK(new_delete_extreme_fixed_sized_accumulation_concurrent_test)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
	FE_REGISTER_CONCURRENT_BENCHMARK(tbb_scalable_memory_resource_extreme_fixed_sized_accumulation_concurrent_test)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();
#endif

	FE_REGISTER_CONCURRENT_BENCHMARK(std_pmr_synchronized_pool_resource_extreme_fixed_sized_accumulation_concurrent_test)
		->Setup(setup_synchronized_pool_resource)->Teardown(teardown_synchronized_pool_resource)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();

	FE_REGISTER_CONCURRENT_BENCHMARK(FE_CMR_extreme_fixed_sized_accumulation_concurrent_test)
		->Setup(setup_concurrent_memory_resource)->Teardown(teardown_concurrent_memory_resource)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();


	FE_REGISTER_CONCURRENT_BENCHMARK(new_delete_extreme_fixed_sized_concurrent_test)
		->Iterations(30000)->ThreadRange(1, l_max_threads)->UseRealTime();

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
	FE_REGISTER_CONCURRENT_BENCHMARK(tbb_scalable_memory_resource_extreme_fixed_sized_concurrent_test)
		->Iterations(30000)->ThreadRange(1, l_max_threads)->UseRealTime();
#endif

	FE_REGISTER_CONCURRENT_BENCHMARK(std_pmr_synchronized_pool_resource_extreme_fixed_sized_concurrent_test)
		->Setup(setup_synchronized_pool_resource)->Teardown(teardown_synchronized_pool_resource)
		->Iterations(30000)->ThreadRange(1, l_max_threads)->UseRealTime();

	FE_REGISTER_CONCURRENT_BENCHMARK(FE_CMR_extreme_fixed_sized_concurrent_test)
		->Setup(setup_concurrent_memory_resource)->Teardown(teardown_concurrent_memory_resource)
		->Iterations(30000)->ThreadRange(1, l_max_threads)->UseRealTime();


	FE_REGISTER_CONCURRENT_BENCHMARK(new_delete_random_size_concurrent_test)
		->Iterations(10000)->ThreadRange(1, l_max_threads)->UseRealTime();

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
	FE_REGISTER_CONCURRENT_BENCHMARK(tbb_scalable_memory_resource_random_size_concurrent_test)
		->Iterations(10000)->ThreadRange(1, l_max_threads)->UseRealTime();
#endif

	FE_REGISTER_CONCURRENT_BENCHMARK(std_pmr_synchronized_pool_resource_random_size_concurrent_test)
		->Setup(setup_synchronized_pool_resource)->Teardown(teardown_synchronized_pool_resource)
		->Iterations(10000)->ThreadRange(1, l_max_threads)->UseRealTime();

	FE_REGISTER_CONCURRENT_BENCHMARK(FE_CMR_random_size_concurrent_test)
		->Setup(setup_concurrent_memory_resource)->Teardown(teardown_concurrent_memory_resource)
		->Iterations(10000)->ThreadRange(1, l_max_threads)->UseRealTime();


	FE_REGISTER_CONCURRENT_BENCHMARK(new_delete_random_size_accumulation_concurrent_test)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();

#if FE_HAS_TBB_SCALABLE_MEMORY_RESOURCE
	FE_REGISTER_CONCURRENT_BENCHMARK(tbb_scalable_memory_resource_random_size_accumulation_concurrent_test)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();
#endif

	FE_REGISTER_CONCURRENT_BENCHMARK(std_pmr_synchronized_pool_resource_random_size_accumulation_concurrent_test)
		->Setup(setup_synchronized_pool_resource)->Teardown(teardown_synchronized_pool_resource)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();

	FE_REGISTER_CONCURRENT_BENCHMARK(FE_CMR_random_size_accumulation_concurrent_test)
		->Setup(setup_concurrent_memory_resource)->Teardown(teardown_concurrent_memory_resource)
		->Iterations(1000)->ThreadRange(1, l_max_threads)->UseRealTime();
}

#undef FE_REGISTER_CONCURRENT_BENCHMARK