// Test cases are auto-generated by the copilot AI.
#include <gtest/gtest.h>
#include <benchmark/benchmark.h>
#include <vector>
#include <random>
#include <FE/list.hxx>

struct counted
{
    static inline int constructions = 0;
    static inline int destructions = 0;

    int value;

    counted() noexcept
        : value(0)
    {
        ++constructions;
    }

    explicit counted(int v) noexcept
        : value(v)
    {
        ++constructions;
    }

    counted(const counted& other) noexcept
        : value(other.value)
    {
        ++constructions;
    }

    counted(counted&& other) noexcept
        : value(other.value)
    {
        ++constructions;
    }

    ~counted() noexcept
    {
        ++destructions;
    }

    bool operator==(const counted& o) const noexcept
    {
        return value == o.value;
    }
};

TEST(XTL_list, default_constructor)
{
    FE::list<int> my_list;
    EXPECT_EQ(my_list.size(), 0u);
    EXPECT_TRUE(my_list.empty());
    EXPECT_EQ(my_list.begin(), my_list.end());
}

TEST(XTL_list, allocator_constructor)
{
    FE::list<int>::allocator_type alloc;
    FE::list<int> l(alloc);
    EXPECT_EQ(l.size(), 0u);
    EXPECT_TRUE(l.empty());
}

TEST(XTL_list, count_value_constructor)
{
    FE::list<int> l(3u, 7);
    EXPECT_EQ(l.size(), 3u);

    std::vector<int> values;
    for (auto it = l.begin(); it != l.end(); ++it)
    {
        values.push_back(*it);
    }

    ASSERT_EQ(values.size(), 3u);
    EXPECT_EQ(values[0], 7);
    EXPECT_EQ(values[1], 7);
    EXPECT_EQ(values[2], 7);
}

TEST(XTL_list, iterator_range_constructor)
{
    std::vector<int> src_vector{ 1, 2, 3, 4 };
    FE::list<int> l(src_vector.begin(), src_vector.end());
    EXPECT_EQ(l.size(), src_vector.size());

    auto it = l.begin();
    for (size_t i = 0; i < src_vector.size(); ++i, ++it)
    {
        EXPECT_EQ(*it, src_vector[i]);
    }
}

TEST(XTL_list, copy_and_modify_are_independent)
{
    FE::list<int> original;
    original.push_back(10);
    original.push_back(20);

    FE::list<int> copy = original;
    EXPECT_EQ(copy.size(), original.size());

    copy.push_back(30);
    EXPECT_EQ(copy.size(), original.size() + 1);
    EXPECT_EQ(original.size(), 2u);
    EXPECT_EQ(copy.back(), 30);
}

TEST(XTL_list, move_constructor_leaves_source_empty)
{
    FE::list<int> src;
    src.push_back(5);
    src.push_back(6);

    FE::list<int> moved = std::move(src);
    EXPECT_EQ(moved.size(), 2u);
    EXPECT_EQ(src.size(), 0u);
    EXPECT_TRUE(src.empty());
    EXPECT_EQ(moved.front(), 5);
    EXPECT_EQ(moved.back(), 6);
}

TEST(XTL_list, initializer_list_constructor)
{
    FE::list<int> l{ 11, 22, 33 };
    EXPECT_EQ(l.size(), 3u);

    int expected[] = { 11, 22, 33 };
    size_t idx = 0;
    for (auto it = l.begin(); it != l.end(); ++it, ++idx)
    {
        EXPECT_EQ(*it, expected[idx]);
    }
}

TEST(XTL_list, destructor_calls_element_destructors)
{
    counted::constructions = 0;
    counted::destructions = 0;

    {
        FE::list<counted> l;
        l.emplace_back(1);
        l.emplace_back(2);
        l.emplace_back(3);

        EXPECT_EQ(counted::constructions, 3);
        EXPECT_EQ(counted::destructions, 0);
        EXPECT_EQ(l.size(), 3u);
    }

    EXPECT_EQ(counted::destructions, 3);
}

/*
    Operation & Modifier tests (snake_case + Allman style)
    - Covers: clear, insert (single, count, range, initializer_list), emplace,
      erase (single, range), push_back/push_front (lvalue/rvalue), emplace_back/front,
      pop_back/pop_front, resize, swap, swap_boundaries.
*/

TEST(XTL_list_modifiers, clear_resets_list)
{
    FE::list<int> l;
    for (int i = 0; i < 5; ++i)
    {
        l.push_back(i + 1);
    }

    EXPECT_EQ(l.size(), 5u);
    l.clear();
    EXPECT_EQ(l.size(), 0u);
    EXPECT_TRUE(l.empty());
    EXPECT_EQ(l.begin(), l.end());
}

TEST(XTL_list_modifiers, insert_single_at_begin_middle_end)
{
    FE::list<int> l;
    l.push_back(1);
    l.push_back(3);

    // insert 2 in the middle
    auto it = l.cbegin();
    ++it; // points to 3
    l.insert(it, 2);
    EXPECT_EQ(l.size(), 3u);

    std::vector<int> expected_mid{ 1, 2, 3 };
    size_t idx = 0;
    for (auto iter = l.begin(); iter != l.end(); ++iter, ++idx)
    {
        EXPECT_EQ(*iter, expected_mid[idx]);
    }

    // insert at end
    l.insert(l.cend(), 4);
    EXPECT_EQ(l.size(), 4u);
    EXPECT_EQ(l.back(), 4);

    // insert at begin
    l.insert(l.cbegin(), 0);
    EXPECT_EQ(l.size(), 5u);
    EXPECT_EQ(l.front(), 0);
}

TEST(XTL_list_modifiers, insert_count_values)
{
    FE::list<int> l;
    l.push_back(1);

    // insert three 9s at end
    FE::list<int>::const_iterator pos = l.cend();
	int data = 9;
    l.insert(pos, 3u, data);
    EXPECT_EQ(l.size(), 4u);

    std::vector<int> expected{ 1, 9, 9, 9 };
    size_t idx = 0;
    for (auto it = l.begin(); it != l.end(); ++it, ++idx)
    {
        EXPECT_EQ(*it, expected[idx]);
    }
}

TEST(XTL_list_modifiers, insert_range_and_initializer_list)
{
    FE::list<int> l{ 10 };
    std::vector<int> range_src{ 20, 30, 40 };
    // insert range before end
    auto pos = l.cend();
    l.insert(pos, range_src.begin(), range_src.end());
    EXPECT_EQ(l.size(), 4u);

    std::vector<int> expected{ 10, 20, 30, 40 };
    size_t idx = 0;
    for (auto it = l.begin(); it != l.end(); ++it, ++idx)
    {
        EXPECT_EQ(*it, expected[idx]);
    }

    // initializer_list insert at begin
    std::initializer_list<int> il{ 5, 6 };
    l.insert(l.cbegin(), il);
    EXPECT_EQ(l.size(), 6u);

    int expected2[] = { 5, 6, 10, 20, 30, 40 };
    idx = 0;
    for (auto it = l.begin(); it != l.end(); ++it, ++idx)
    {
        EXPECT_EQ(*it, expected2[idx]);
    }
}

TEST(XTL_list_modifiers, emplace_variants_and_push_pop)
{
    FE::list<counted> lc;
    counted::constructions = 0;
    counted::destructions = 0;

    // emplace_back constructs counted with int
    lc.emplace_back(7);
    EXPECT_EQ(lc.size(), 1u);
    EXPECT_EQ(lc.back().value, 7);

    // emplace_front constructs counted with int
    lc.emplace_front(3);
    EXPECT_EQ(lc.size(), 2u);
    EXPECT_EQ(lc.front().value, 3);

    // push_back rvalue and lvalue
    counted tmp(9);
    lc.push_back(tmp);
    EXPECT_EQ(lc.size(), 3u);
    EXPECT_EQ(lc.back().value, 9);

    lc.push_back(counted(11));
    EXPECT_EQ(lc.back().value, 11);

    // pop_back/pop_front
    lc.pop_back();
    EXPECT_EQ(lc.size(), 3u);
    lc.pop_front();
    EXPECT_EQ(lc.size(), 2u); // after two pops
}

TEST(XTL_list_modifiers, erase_single_and_range)
{
    FE::list<int> l;
    for (int i = 1; i <= 6; ++i)
    {
        l.push_back(i);
    }
    EXPECT_EQ(l.size(), 6u);

    // erase middle element (value 3)
    auto it = l.cbegin();
    it = std::next(it, 2);
    l.erase(it);
    EXPECT_EQ(l.size(), 5u);

    std::vector<int> expected_after_erase{ 1, 2, 4, 5, 6 };
    size_t idx = 0;
    for (auto iter = l.begin(); iter != l.end(); ++iter, ++idx)
    {
        EXPECT_EQ(*iter, expected_after_erase[idx]);
    }

    // erase a range: remove first two elements (1,2)
    auto first = l.cbegin();
    auto last = std::next(first, 2);
    l.erase(first, last);
    EXPECT_EQ(l.size(), 2u);

    std::vector<int> expected_after_range_erase{ 5, 6 };
    idx = 0;
    for (auto iter = l.begin(); iter != l.end(); ++iter, ++idx)
    {
        EXPECT_EQ(*iter, expected_after_range_erase[idx]);
    }
}

TEST(XTL_list_modifiers, resize_grows_and_shrinks)
{
    FE::list<int> l;
    l.resize(3);
    EXPECT_EQ(l.size(), 3u);

    // new elements default-constructed to 0
    std::vector<int> expected_grow{ 0, 0, 0 };
    size_t idx = 0;
    for (auto it = l.begin(); it != l.end(); ++it, ++idx)
    {
        EXPECT_EQ(*it, expected_grow[idx]);
    }

    // shrink to 1
    l.resize(1);
    EXPECT_EQ(l.size(), 1u);
    EXPECT_EQ(l.front(), 0);
    EXPECT_EQ(l.back(), 0);
}

TEST(XTL_list_modifiers, swap_and_swap_boundaries)
{
    // swap()
    FE::list<int> a{ 1, 2, 3 };
    FE::list<int> b{ 10, 20 };
    a.swap(b);
    EXPECT_EQ(a.size(), 2u);
    EXPECT_EQ(b.size(), 3u);

    std::vector<int> expected_a{ 10, 20 };
    size_t idx = 0;
    for (auto it = a.begin(); it != a.end(); ++it, ++idx)
    {
        EXPECT_EQ(*it, expected_a[idx]);
    }

    // swap_boundaries() size == 2
    FE::list<int> s2{ 100, 200 };
    s2.swap_boundaries();
    EXPECT_EQ(s2.front(), 200);
    EXPECT_EQ(s2.back(), 100);

    // swap_boundaries() size >= 3
    FE::list<int> s3{ 1, 2, 3, 4, 5 };
    int old_front = s3.front();
    int old_back = s3.back();
    s3.swap_boundaries();
    EXPECT_EQ(s3.front(), old_back);
    EXPECT_EQ(s3.back(), old_front);

    auto it = s3.begin();
    ++it;
    EXPECT_EQ(*it, 2);
}

/*
  Fuzz-style benchmarks for FE::list constructors using Google Benchmark.
  - All benchmark functions use snake_case and Allman style braces.
  - The benchmark range (state.range(0)) is interpreted as the element count for
    constructors that produce lists of elements (count/value, range, copy, move).
*/

static void fuzztest_list_default_constructor(benchmark::State& state)
{
    std::size_t reps = static_cast<std::size_t>(state.range(0));

    for (auto _ : state)
    {
        for (std::size_t i = 0; i < reps; ++i)
        {
            FE::list<int> l;
            benchmark::DoNotOptimize(l);
        }
    }
}
BENCHMARK(fuzztest_list_default_constructor)
    ->Arg(1)
    ->Arg(10)
    ->Arg(100)
    ->Arg(1000);

static void fuzztest_list_count_value_constructor(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));
    std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<int> dist(INT_MIN, INT_MAX);

    for (auto _ : state)
    {
        int value = static_cast<int>(dist(rng));
        FE::list<int> l(element_count, value);
        benchmark::DoNotOptimize(l);
    }
}
BENCHMARK(fuzztest_list_count_value_constructor)
    ->RangeMultiplier(10)
    ->Range(1, 10000);

static void fuzztest__list_range_constructor(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));
    std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<int> dist(INT_MIN, INT_MAX);

    // prepare the source vector once (outside the timed loop)
    std::vector<int> src;
    src.reserve(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        src.push_back(static_cast<int>(dist(rng)));
    }

    for (auto _ : state)
    {
        FE::list<int> l(src.begin(), src.end());
        benchmark::DoNotOptimize(l);
    }
}
BENCHMARK(fuzztest__list_range_constructor)
    ->RangeMultiplier(10)
    ->Range(1, 10000);

static void fuzztest__list_copy_constructor(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));
    std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<int> dist(INT_MIN, INT_MAX);

    // prepare the source list once
    std::vector<int> src_vals;
    src_vals.reserve(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        src_vals.push_back(static_cast<int>(dist(rng)));
    }
    FE::list<int> src_list(src_vals.begin(), src_vals.end());

    for (auto _ : state)
    {
        FE::list<int> copy = src_list;
        benchmark::DoNotOptimize(copy);
    }
}
BENCHMARK(fuzztest__list_copy_constructor)
    ->RangeMultiplier(10)
    ->Range(1, 10000);

static void fuzztest_list_move_constructor(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));
    std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<int> dist(INT_MIN, INT_MAX);

    // prepare a source vector to re-create lists to move from
    std::vector<int> src_vals;
    src_vals.reserve(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        src_vals.push_back(static_cast<int>(dist(rng)));
    }

    for (auto _ : state)
    {
        // create a temporary list and move it; this measures move-construction
        // but the construction overhead is necessarily part of the operation.
        FE::list<int> src(src_vals.begin(), src_vals.end());
        FE::list<int> moved = std::move(src);
        benchmark::DoNotOptimize(moved);
    }
}
BENCHMARK(fuzztest_list_move_constructor)
    ->RangeMultiplier(10)
    ->Range(1, 10000);



// Benchmarks for emplace_front and emplace_back operations
static void std_list_emplace_front(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));

    // prepare values once per benchmark invocation to remove RNG noise
    std::vector<int> values;
    values.resize(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        values[i] = static_cast<int>(i);
    }

    for (auto _ : state)
    {
        std::list<int> l;
        for (std::size_t i = 0; i < element_count; ++i)
        {
            l.emplace_front(values[i]);
        }
        benchmark::DoNotOptimize(l);
        benchmark::ClobberMemory();
    }
}
BENCHMARK(std_list_emplace_front)
    ->RangeMultiplier(10)
    ->Range(1, 10000);

static void frogman_list_emplace_front(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));

    // prepare values once per benchmark invocation to remove RNG noise
    std::vector<int> values;
    values.resize(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        values[i] = static_cast<int>(i);
    }

    for (auto _ : state)
    {
        FE::list<int> l;
        for (std::size_t i = 0; i < element_count; ++i)
        {
            l.emplace_front(values[i]);
        }
        benchmark::DoNotOptimize(l);
        benchmark::ClobberMemory();
    }
}
BENCHMARK(frogman_list_emplace_front)
    ->RangeMultiplier(10)
    ->Range(1, 10000);

static void std_list_emplace_back(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));

    // prepare values once per benchmark invocation to remove RNG noise
    std::vector<int> values;
    values.resize(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        values[i] = static_cast<int>(i);
    }

    for (auto _ : state)
    {
        std::list<int> l;
        for (std::size_t i = 0; i < element_count; ++i)
        {
            l.emplace_back(values[i]);
        }
        benchmark::DoNotOptimize(l);
        benchmark::ClobberMemory();
    }
}
BENCHMARK(std_list_emplace_back)
    ->RangeMultiplier(10)
    ->Range(1, 10000);

static void frogman_list_emplace_back(benchmark::State& state)
{
    std::size_t element_count = static_cast<std::size_t>(state.range(0));

    // prepare values once per benchmark invocation to remove RNG noise
    std::vector<int> values;
    values.resize(element_count);
    for (std::size_t i = 0; i < element_count; ++i)
    {
        values[i] = static_cast<int>(i);
    }

    for (auto _ : state)
    {
        FE::list<int> l;
        for (std::size_t i = 0; i < element_count; ++i)
        {
            l.emplace_back(values[i]);
        }
        benchmark::DoNotOptimize(l);
        benchmark::ClobberMemory();
    }
}
BENCHMARK(frogman_list_emplace_back)
    ->RangeMultiplier(10)
    ->Range(1, 10000);